name: demo pipeline

on:
  push:
    branches: [ "test" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # ----------------------------
      # Step 1: Checkout code
      # ----------------------------
      - name: Checkout code
        uses: actions/checkout@v4

      # ----------------------------
      # Step 2: Set up Java
      # ----------------------------
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # ----------------------------
      # Step 3.1: Run tests
      # ----------------------------
      - name: Run tests
        run: mvn test

      # ----------------------------
      # Step 3: Build artifact without testing
      # ----------------------------

      - name: Build artifact
        run: mvn clean install -DskipTests

      # ----------------------------
      # Step 4: Login to Docker Hub
      # ----------------------------
      - name: Login to Docker Hub
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

      # ----------------------------
      # Step 5: Build Docker images
      # ----------------------------
      - name: Build Docker images
        run: |
          docker build -t calften/demo-cicd:v1 --build-arg APP_VERSION=v1 .
          docker build -t calften/demo-cicd:v2 --build-arg APP_VERSION=v2 .
          docker build -t calften/demo-nginx:latest ./nginx

      # ----------------------------
      # Step 6: Push Docker images
      # ----------------------------
      - name: Push Docker images
        run: |
          docker push calften/demo-cicd:v1
          docker push calften/demo-cicd:v2
          docker push calften/demo-nginx:latest

  deploy:
    needs: build
    runs-on: [ Linux ]
    steps:
      - name: Remove and pull image v1 from Docker Hub
        run: |
          sudo docker rm -f demo-v1 2>/dev/null || true
          sudo docker pull calften/demo-cicd:v1

      - name: Remove and pull image v2 from Docker Hub
        run: |
          sudo docker rm -f demo-v2 2>/dev/null || true
          sudo docker pull calften/demo-cicd:v2

      - name: Create Docker network
        run: sudo docker network create demo-net || true

      - name: Run demo-v1
        run: |
          sudo docker run -d --name demo-v1 --network demo-net -p 8080:8080 calften/demo-cicd:v1

      - name: Run demo-v2
        run: |
          sudo docker run -d --name demo-v2 --network demo-net -p 8081:8080 calften/demo-cicd:v2

      - name: Run custom NGINX container
        run: |
          sudo docker rm -f nginx 2>/dev/null || true
          sudo docker pull calften/demo-nginx:latest
          sudo docker run -d \
            --name nginx \
            --network demo-net \
            -p 80:80 \
            calften/demo-nginx:latest
      

      - name: Output URLs
        run: |
          echo "✅ Canary deployment complete!"
          echo "NGINX canary URL: http://localhost"
          echo "Direct v1 URL: http://localhost:8081"
          echo "Direct v2 URL: http://localhost:8082"
