name: demo pipeline

on:
  push:
    branches: [ "test" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # ----------------------------
      # Step 1: Checkout code
      # ----------------------------
      - name: Checkout code
        uses: actions/checkout@v4

      # ----------------------------
      # Step 2: Set up Java
      # ----------------------------
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # ----------------------------
      # Step 3: Build Spring Boot app
      # ----------------------------
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # ----------------------------
      # Step 4: Login to Docker Hub
      # ----------------------------
      - name: Login to Docker Hub
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

      # ----------------------------
      # Step 5: Build Docker images
      # ----------------------------
      - name: Build Docker images
        run: |
          docker build -t calften/demo-cicd:v1 --build-arg APP_VERSION=v1 .
          docker build -t calften/demo-cicd:v2 --build-arg APP_VERSION=v2 .

      # ----------------------------
      # Step 6: Push Docker images
      # ----------------------------
      - name: Push Docker images
        run: |
          docker push calften/demo-cicd:v1
          docker push calften/demo-cicd:v2

  deploy:
    needs: build
    runs-on: [Linux]
    steps:
      - name: Pull image from docker hub
        run: sudo docker pull calften/demo-cicd:latest

      # ----------------------------
      # Step 7: Create Docker network
      # ----------------------------
      - name: Create Docker network
        run: docker network create demo-net || true

      # ----------------------------
      # Step 8: Run app containers
      # ----------------------------
      - name: Run demo-v1
        run: |
          docker rm -f demo-v1 2>/dev/null || true
          docker run -d --name demo-v1 --network demo-net -p 8080:8080 calften/demo-cicd:v1

      - name: Run demo-v2
        run: |
          docker rm -f demo-v2 2>/dev/null || true
          docker run -d --name demo-v2 --network demo-net -p 8081:8080 calften/demo-cicd:v2

      # ----------------------------
      # Step 9: Run NGINX container using existing nginx folder
      # ----------------------------


      # ----------------------------
      # Step 10: Output URLs
      # ----------------------------
      - name: Output URLs
        run: |
          echo "✅ Canary deployment complete!"
          echo "NGINX canary URL: http://localhost"
          echo "Direct v1 URL: http://localhost:8080"
          echo "Direct v2 URL: http://localhost:8081"
