name: demo-canary-ec2

on:
  push:
    branches: ["test-adammeh"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # ----------------------------
      # Step 1: Checkout code
      # ----------------------------
      - name: Checkout code
        uses: actions/checkout@v4

      # ----------------------------
      # Step 2: Set up Java
      # ----------------------------
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # ----------------------------
      # Step 3: Determine version to build
      # ----------------------------
      - name: Determine build version
        id: build_target
        run: |
          echo "Checking if v1 exists on Docker Hub..."
          if docker pull adammeh/demo-cicd:v1 >/dev/null 2>&1; then
            echo "v1 exists, building v2"
            echo "VERSION=v2" >> $GITHUB_OUTPUT
          else
            echo "v1 does not exist, building v1"
            echo "VERSION=v1" >> $GITHUB_OUTPUT
          fi

      # ----------------------------
      # Step 4: Build Docker image
      # ----------------------------
      - name: Build Docker image
        run: |
          mvn clean install -DskipTests
          docker build -t adammeh/demo-cicd:${{ steps.build_target.outputs.VERSION }} --build-arg APP_VERSION=${{ steps.build_target.outputs.VERSION }} .

      # ----------------------------
      # Step 5: Login to Docker Hub
      # ----------------------------
      - name: Login to Docker Hub
        run: docker login -u "${{ secrets.DOCKER_USERNAME2 }}" -p "${{ secrets.DOCKER_PASSWORD2 }}"

      # ----------------------------
      # Step 6: Push Docker image
      # ----------------------------
      - name: Push Docker image
        run: docker push adammeh/demo-cicd:${{ steps.build_target.outputs.VERSION }}

      # ----------------------------
      # Step 7: Choose NGINX config file
      # ----------------------------
      - name: Set NGINX config file
        id: nginx_file
        run: |
          if [ "${{ steps.build_target.outputs.VERSION }}" == "v1" ]; then
            echo "file=nginx-v1.conf" >> $GITHUB_OUTPUT
          else
            echo "file=nginx-canary.conf" >> $GITHUB_OUTPUT
          fi

      # ----------------------------
      # Step 8: Copy NGINX config to EC2
      # ----------------------------
      - name: Copy NGINX config
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ${{ steps.nginx_file.outputs.file }}
          target: "/home/ubuntu/nginx/"
          overwrite: true

      # ----------------------------
      # Step 9: SSH into EC2 and deploy
      # ----------------------------
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Logging into Docker Hub on EC2..."
            docker login -u "${{ secrets.DOCKER_USERNAME2 }}" -p "${{ secrets.DOCKER_PASSWORD2 }}"

            echo "Creating Docker network if not exists..."
            docker network create demo-net || true

            # ----------------------------
            # Step 1: Ensure old container v1 is running
            # ----------------------------
            if ! [ "$(docker ps -q -f name=demo-v1)" ]; then
              echo "Starting old container v1..."
              docker run -d --name demo-v1 --network demo-net -p 8081:8080 adammeh/demo-cicd:v1
            fi

            # ----------------------------
            # Step 2: Stop and start new container if v2
            # ----------------------------
            if [ "${{ steps.build_target.outputs.VERSION }}" == "v2" ]; then
              docker rm -f demo-v2 2>/dev/null || true
              docker run -d --name demo-v2 --network demo-net -p 8082:8080 adammeh/demo-cicd:v2
            fi

            # ----------------------------
            # Step 3: Restart NGINX
            # ----------------------------
            docker rm -f nginx 2>/dev/null || true
            docker run -d --name nginx --network demo-net -p 80:80 -v /home/ubuntu/nginx:/etc/nginx:ro nginx:latest

            echo "✅ Deployment complete!"
            echo "NGINX URL: http://<your-ec2-public-ip>"
            echo "Direct v1 URL: http://<your-ec2-public-ip>:8081"
            echo "Direct v2 URL: http://<your-ec2-public-ip>:8082"
