name: demo-canary-ec2

on:
  push:
    branches: ["test-adammeh"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # ----------------------------
      # Step 1: Checkout code
      # ----------------------------
      - name: Checkout code
        uses: actions/checkout@v4

      # ----------------------------
      # Step 2: Set up Java
      # ----------------------------
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # ----------------------------
      # Step 3: Decide whether to build v1 or v2
      # ----------------------------
      - name: Decide Docker tag
        id: decide-tag
        run: |
          if docker pull adammeh/demo-cicd:v1 >/dev/null 2>&1; then
            echo "tag=v2" >> $GITHUB_OUTPUT
          else
            echo "tag=v1" >> $GITHUB_OUTPUT
          fi

      # ----------------------------
      # Step 4: Build Docker image
      # ----------------------------
      - name: Build Docker image
        run: |
          mvn clean install -DskipTests
          docker build -t adammeh/demo-cicd:${{ steps.decide-tag.outputs.tag }} \
            --build-arg APP_VERSION=${{ steps.decide-tag.outputs.tag }} .

      # ----------------------------
      # Step 5: Login to Docker Hub
      # ----------------------------
      - name: Login to Docker Hub
        run: docker login -u "${{ secrets.DOCKER_USERNAME2 }}" -p "${{ secrets.DOCKER_PASSWORD2 }}"

      # ----------------------------
      # Step 6: Push Docker image
      # ----------------------------
      - name: Push Docker image
        run: docker push adammeh/demo-cicd:${{ steps.decide-tag.outputs.tag }}

      # ----------------------------
      # Step 7: Copy NGINX config to EC2
      # ----------------------------
      - name: Copy NGINX config to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "nginx.conf"
          target: "/home/ubuntu/nginx/"
          overwrite: true

      # ----------------------------
      # Step 8: SSH into EC2 and deploy
      # ----------------------------
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Logging into Docker Hub on EC2..."
            docker login -u "${{ secrets.DOCKER_USERNAME2 }}" -p "${{ secrets.DOCKER_PASSWORD2 }}"

            echo "Creating Docker network if not exists..."
            docker network create demo-net || true

            echo "Deploying v1..."
            docker rm -f demo-v1 2>/dev/null || true
            docker pull adammeh/demo-cicd:v1 || true
            docker run -d --name demo-v1 --network demo-net -p 8081:8080 adammeh/demo-cicd:v1 || true

            echo "Deploying v2 (if exists)..."
            if docker manifest inspect adammeh/demo-cicd:v2 > /dev/null 2>&1; then
              docker rm -f demo-v2 2>/dev/null || true
              docker pull adammeh/demo-cicd:v2
              docker run -d --name demo-v2 --network demo-net -p 8082:8080 adammeh/demo-cicd:v2
            fi

            echo "Restarting NGINX..."
            docker rm -f nginx 2>/dev/null || true
            docker run -d --name nginx --network demo-net -p 80:80 -v /home/ubuntu/nginx:/etc/nginx:ro nginx:latest

            echo "✅ Deployment complete!"
            echo "NGINX Canary URL: http://<your-ec2-ip>"
            echo "Direct v1 URL:   http://<your-ec2-ip>:8081"
            echo "Direct v2 URL:   http://<your-ec2-ip>:8082"
