name: demo-canary-ec2

on:
  push:
    branches: [ "test-adammeh" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # ----------------------------
      # Step 1: Checkout code
      # ----------------------------
      - name: Checkout code
        uses: actions/checkout@v4

      # ----------------------------
      # Step 2: Set up Java
      # ----------------------------
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # ----------------------------
      # Step 3: Build Spring Boot app (for new version only)
      # ----------------------------
      - name: Build new Docker image (v2)
        run: |
          mvn clean install -DskipTests
          docker build -t adammeh/demo-cicd:v2 --build-arg APP_VERSION=v2 .

      # ----------------------------
      # Step 4: Push v2 to Docker Hub
      # ----------------------------
      - name: Push Docker image v2
        run: docker push adammeh/demo-cicd:v2

      # ----------------------------
      # Step 5: SSH into EC2 and deploy
      # ----------------------------
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Logging into Docker Hub..."
            docker login -u "${{ secrets.DOCKER_USERNAME2 }}" -p "${{ secrets.DOCKER_PASSWORD2 }}"

            echo "Pulling new image v2..."
            docker pull adammeh/demo-cicd:v2

            echo "Creating Docker network..."
            docker network create demo-net || true

            # ----------------------------
            # Step 1: Run old container v1 if it doesn't exist
            # ----------------------------
            if ! [ "$(docker ps -q -f name=demo-v1)" ]; then
              echo "Starting old container v1..."
              docker run -d --name demo-v1 --network demo-net -p 8081:8080 adammeh/demo-cicd:v1
            fi

            # ----------------------------
            # Step 2: Start new container v2
            # ----------------------------
            docker rm -f demo-v2 2>/dev/null || true
            docker run -d --name demo-v2 --network demo-net -p 8082:8080 adammeh/demo-cicd:v2

            # ----------------------------
            # Step 3: Run NGINX for canary
            # ----------------------------
            docker rm -f nginx 2>/dev/null || true
            docker run -d --name nginx --network demo-net -p 80:80 -v /home/ubuntu/nginx:/etc/nginx:ro nginx:latest

            echo "✅ Canary deployment complete!"
            echo "NGINX canary URL: http://<your-ec2-public-ip>"
            echo "Direct v1 URL: http://<your-ec2-public-ip>:8081"
            echo "Direct v2 URL: http://<your-ec2-public-ip>:8082"

